---
title: "Philly Bail"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
all <- read.csv("../parsed1.csv")

```

```{r}

#This is a histogram for the distribution of Offense Date from 2015-Now
library(tidyverse)
my_data <- as_tibble(all)
my_data$offense_date <- as.Date(all$offense_date, format = "%m/%d/%y")
x <- my_data %>% filter(offense_date > '2015-01-01')
hist(x$offense_date, breaks = 'months',
     xlab = "Offense Date",
     ylab = "Density")
```

```{r}
library(tidyverse)
my_data <- as_tibble(all)
y <- my_data %>% filter(bail_amount < 100000)
hist(y$bail_amount, breaks = "fd", 
     main = "Histogram of Bail Amount",
     xlab = "Bail Amount",
     ylab = "Frequency")
```

```{r}
library(lubridate)
t <- "1:36:22 PM"
time_of_day = hour(parse_date_time(all$prelim_hearing_time, '%I:%M %p', tz = "America/New_York"))
bail_amount = all$bail_amount
plot(time_of_day, bail_amount, 
     ylab = "Amount of Bail",
     xlab = "Time of Day"
     )
#hist(hour(date_time), breaks = 30)
```

```{r}
#This function tries to correctly parse the date of birth from the date of birth column and changes it to years
foo <- function(x, year=1968){
  k <- year(x) %% 100
  year(x) <- ifelse(k > year %% 100, 1900+m, 2000+m)
  x
}
x <- foo(as.Date(all$dob, format = "%m/%d/%y"), 1920)

bail_in_thousands <- all$bail_amount / 1000
plot(x, bail_in_thousands,
     xlab = "Date of Birth",
     ylab = "Bail Amount in Thousands")
```

```{r}
data2 <- read_csv("../parsed2.csv")
data2 <- subset(data2, select=c(bail_amount, bail_paid, felonies, misdemeanors, summaries))
write_csv(data2, "parsed3.csv")
```